#!/usr/bin/env bash


if [ $SHELL != /bin/bash ]; then
    echo -e "Setting shell to bash. Logout to have bash has default shell language."
    chsh -s /bin/bash
fi

if [ ! -f ~/.bash_aliases ]; then
    echo -e "Install bash file. For local dev files, see ~/dotFiles/envFiles."
    ln -s ~/dotFiles/envFiles/bash_aliases ~/.bash_aliases
fi

if [ ! -d ~/.vim ]; then
    echo -e "Install vim plugins."
    ln -s ~/dotFiles/vim ~/.vim
fi

if [ ! -f ~/.vimrc ]; then
    echo -e "Install vim configurations."
    ln -s ~/dotFiles/vimrc ~/.vimrc
fi

if [ ! -f ~/.gitconfig ]; then
    echo -e "Install git configs"
    ln -s ~/dotFiles/gitconfig ~/.gitconfig
fi

if [ ! -f ~/.git-prompt.sh ]; then
    echo -e "git prompt."
    ln -s ~/dotFiles/git-prompt.sh ~/.git-prompt.sh
fi

if [ ! -f ~/.git-completion.bash ]; then
    echo -e "git auto completion."
    ln -s ~/dotFiles/git-completion.bash ~/.git-completion.bash
fi

if [ ! -f ~/.gitdiff_meld.py ]; then
    echo -e "git diff with meld."
    ln -s ~/dotFiles/gitdiff_meld.py ~/.gitdiff_meld.py
fi

echo -e "Done"