#!/usr/bin/env bash

if [ $(uname) == 'Darwin' ]; then
    if [ ! -f $(which brew) ]; then
        echo "Darwin: Install brew"
        /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    fi
    brew install fish
else
    if [ -f ./install_apt ]; then
        echo -e "Install apt package"
        sudo bash ./install_apt
    fi
fi

if [ $SHELL != $(which fish) ]; then
    echo -e "Setting shell to fish. Logout to have bash has default shell language."
    chsh -s $(which fish)
fi

if [ ! -f "~/.config/fish/config.fish" ]; then
    echo -e "Install fish file."
    ln -s ~/dotFiles/envFiles/config.fish ~/.config/fish/config.fish
fi

if [ ! -d ~/.vim ]; then
    echo -e "Install vim plugins."
    ln -s ~/dotFiles/vim ~/.vim
fi

if [ ! -f ~/.vimrc ]; then
    echo -e "Install vim configurations."
    ln -s ~/dotFiles/vimrc ~/.vimrc
fi

if [ ! -f ~/.gitconfig ]; then
    echo -e "Install git configs"
    ln -s ~/dotFiles/gitconfig ~/.gitconfig
fi



echo -e "Done"
