#!/usr/bin/env bash

#if not running interactively, don't do anything
[ -z "$PS1" ] && return

# colors!
readonly RED="\[\033[31m\]"
readonly GREEN="\[\033[32m\]"
readonly YELLOW="\[\033[33m\]"
readonly BLUE="\[\033[34m\]"
readonly MAGENTA="\[\033[35m\]"
readonly CYAN="\[\033[36m\]"
readonly WHITE="\[\033[37m\]"
readonly END="\[\033[0m\]"

# ALIASES
alias gitka='gitk --all'
alias cd..='cd ..'
alias u='cd ..'
alias rm='rm -r'
alias cp='cp -r'
alias mkdir='mkdir -p'
alias h='history'
alias mv='mv -i'
alias grep='grep --color=auto'
alias ls='ls -h'
alias la='ls -a'
alias ll='ls -l'
alias r='refresh'
alias lg='ls -1 | grep -i \!*'
alias eg='env | grep -i \!*'
alias dc='docker-compose'
if [ $(uname) == 'Darwin' ]; then
    alias ls='ls -G'
else
    alias ls='ls --color=auto'
fi

# docker aliases
alias drmae='docker rm $(docker ps -qa --no-trunc --filter "status=exited")'
alias drmi='docker rmi $(docker images --filter "dangling=true" -q --no-trunc)'


if [ -f ~/.git-prompt.sh ]; then
    echo -e "\033[0;32mSourcing git prompt script\033[0m"
    . ~/.git-prompt.sh
    export PS1="${WHITE}--- \T \u@\h ${GREEN}\w ${CYAN}\$(__git_ps1) ${END} ${SELECT}\n>>> "
fi


export WORKON_HOME=$HOME/virtualenvs/

# ENVIRONMENT VARIABLES
export EDITOR=vim

if [ -f ~/.local_env.bash ]; then
    echo -e "\033[0;32mSourcing Local Environment \033[0m"
    . ~/.local_env.bash
fi

if [ -f ~/.git-completion.bash ]; then
    echo -e "\033[0;32mSourcing Git Completion Script \033[0m"
    . ~/.git-completion.bash
    set autolist=ambiguous
fi

if [ -f /usr/local/bin/virtualenvwrapper.sh ]; then
    echo -e "\033[0;32mSourcing virtualenvwrapper.sh (/usr/local/bin) \033[0m (virtualenv home: ${WORKON_HOME})"
    source /usr/local/bin/virtualenvwrapper.sh
elif [ -f /usr/bin/virtualenvwrapper.sh ]; then
    echo -e "\033[0;32mSourcing virtualenvwrapper.sh (/usr/bin) \033[0m (virtualenv home: ${WORKON_HOME})"
    source /usr/bin/virtualenvwrapper.sh
else
    echo -e "\033[0;31mvirtualenvwrapper is not installed. Please run pip install --user virtualenvwrapper \033[0m"
fi

if [ -f ~/.dev_env.bash ]; then
    echo -e "\033[0;32mSourcing Development Environment \033[0m"
    source ~/.dev_env.bash
fi

export PATH="/usr/local/sbin:/usr/local/bin:$PATH"

[[ -s $HOME/.pythonz/etc/bashrc ]] && source $HOME/.pythonz/etc/bashrc
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*

