#!/usr/bin/tcsh


alias gitka     'gitk --all'
###########################################################################################################
# tab features
###########################################################################################################
set filec
set autolist

###########################################################################################################
# functions
###########################################################################################################


# colors!
set     red="%{\033[1;31m%}"
set   green="%{\033[0;32m%}"
set  yellow="%{\033[1;33m%}"
set    blue="%{\033[1;34m%}"
set magenta="%{\033[1;35m%}"
set    cyan="%{\033[1;36m%}"
set   white="%{\033[0;37m%}"
set     end="%{\033[0m%}" # This is needed at the end... :(

# Setting the actual prompt.  I made two separate versions for you to try, pick
# # whichever one you like better, and change the colors as you want.  Just don't
# # mess with the ${end} guy in either line...  Comment out or delete the prompt you don't use.
#
# set prompt="${green}%n${blue}@%m ${white}%~ ${green}%%${end} "
# set prompt="[${green}%n${blue}@%m ${white}%~ ]${end} "
#
# # Clean up after ourselves...
# unset red green yellow blue magenta cyan yellow white end
## prompt feature
alias __git_current_branch 'git rev-parse --abbrev-ref HEAD >& /dev/null && echo "(`git rev-parse --abbrev-ref HEAD`) "'
#alias _prompt 'set prompt="%U%T%u:`whoami`:%B$cwd%b: > "'
# set prompt="%U%T%u:`whoami`:%B%~%b`__git_current_branch` > "
setenv PROJECT_PROMPT
alias precmd 'set prompt="${magenta}$PROJECT_PROMPT${white}%U%T%u:`whoami`:${green}%B%~%b ${cyan}`__git_current_branch`${end}> "'
#i-search-back bound like on bash (Ctrl+R)
bindkey "^R" i-search-back

alias cd.. 		'cd ..'
alias u         'cd ..'
alias .. 		'cd ..'
alias rm 		'rm -r'
alias cp 		'cp -r'
alias mkdir     'mkdir -p'

alias mv 		'mv -i'
alias grep      'grep --color=auto'

# only for linux
alias ls        'ls -h'
alias la        'ls -a'
alias lt        'ls -lrt'
alias ll 		'ls -l'
alias r 'refresh'
alias e 'exit'
alias E 'exit'
alias hg 'history | grep \!*'
alias lg 'ls -1 | grep -i \!*'
alias cg 'cd `ls | grep -i \!*`'
alias eg 'env | grep -i \!*'
alias sourceMe  'source ~/.cshrc'
alias sm 'sourceMe'




# Addition of path to bin from dotFiles repo
setenv PATH ${PATH}:$HOME/dotFiles/bin
setenv EDITOR vim

set nobeep




if ( -e ~/.local_env ) then
    echo "Sourcing Local Environment"
    source ~/.local_env
endif

if ( -e ~/.git-completion.tcsh) then
    echo "Sourcing git completion script"
    source ~/.git-completion.tcsh
    set autolist=ambiguous # adviced in the how to use
endif

if ( -e ~/.dev_env ) then
    echo "Sourcing development_environment"
    source ~/.dev_env
endif



