#!/usr/bin/tcsh

alias ls        'ls --auto=color'

# Aliases odoo
#
# v._neutral_env:
# - sets ODOO_PROJECT env variable.
# - sets the prompt, the title of the tab and cd to the project folder.
# - requires the name of the project as the first argument.

alias v.project 'source ~/virutalenvs/odoo_job_hunting/bin/activate.csh; cd ~/odoo_job_hunting/main'




